version: '3.9'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example_next_app
    stdin_open: true
    ports:
      - '3000:3000'
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - COGNITO_CLIENT_ID=xxxxxxx
      - COGNITO_DOMAIN_NAME_URL=https://xxxxxxxx.auth.xxxxxxxx.amazoncognito.com
      - COGNITO_LOGIN_GRANT_TYPE=authorization_code
      - COGNITO_LOGIN_REDIRECT_URL=http://localhost:3000/oauth/cognito
      - COGNITO_LOGIN_RESPONSE_TYPE=code
      - COGNITO_LOGIN_SCOPE=email+openid
      - COGNITO_LOGOUT_REDIRECT_URL=http://localhost:3000/oauth/cognito/logout
      - COOKIE_SESSION_NAME=nodejs-cognito-oauth
      - COOKIE_SESSION_SECRET=xxxxxx
